# Generated by Django 5.1.6 on 2025-06-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Заметки"),
        ),
    ]
