# Generated by Django 5.1.6 on 2025-05-19 12:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_remove_cartitem_price"),
        ("catalog", "0004_alter_productextraimage_product"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cartitem",
            name="unique_product_in_cart",
        ),
        migrations.AlterField(
            model_name="cart",
            name="session_key",
            field=models.CharField(
                blank=True,
                max_length=40,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_session_key",
                        message="Некорректный ключ сессии.",
                        regex="^[a-zA-Z0-9]{20,40}$",
                    )
                ],
                verbose_name="Ключ сессии",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(fields=["user"], name="cart_cart_user_id_b645f9_idx"),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["session_key"], name="cart_cart_session_5e1af5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(fields=["cart"], name="cart_cartit_cart_id_4fb076_idx"),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["product"], name="cart_cartit_product_985dba_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("product__isnull", False)),
                fields=("cart", "product"),
                name="unique_product_in_cart",
            ),
        ),
    ]
