# Generated by Django 5.1.7 on 2025-03-31 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = []
