# Generated by Django 5.1.7 on 2025-04-14 11:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20250331_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='_actual_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Цена со скидкой'),
        ),
        migrations.AddField(
            model_name='product',
            name='availability_status',
            field=models.CharField(choices=[('in_stock', 'В наличии'), ('backorder', 'Под заказ'), ('unavailable', 'Недоступен')], db_index=True, default='in_stock', editable=False, max_length=20, verbose_name='Статус наличия'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_for_order',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Доступен к заказу'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['availability_status', 'stock'], name='availability_idx'),
        ),
    ]
