# Generated by Django 5.1.7 on 2025-04-15 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product__actual_price_product_availability_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productextraimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='catalog.product'),
        ),
    ]
